### ISSUE TITLE
NonCausalTemporalLayer implementation

### ISSUE THREAD

**Issue by kobybibas** [ben-hayes/beat-tracking-tcn#1]
Hi,
Thanks for this very helpful repository. 

In the NonCausalTemporalLayer is seems that conv1 is not used:
https://github.com/ben-hayes/beat-tracking-tcn/blob/87c580cf2a2a2529451fa63eb61f09331ea8efa5/beat_tracking_tcn/models/tcn.py#L101

Did I miss somthing?
Do you think it is a problem?

Thanks again,
Koby

**Comment by ben-hayes** [comment]
Hey Koby,

Great catch! Thanks so much for pointing this out. You definitely didn't miss anything — that's a typo and mistake on my part.

Have just pushed a fix. It'll be interesting to see how the model fares with this fixed.

Best

Ben :)
