### ISSUE TITLE
prepare custom  dataset

### ISSUE THREAD

**Issue by SutirthaChakraborty** [ben-hayes/beat-tracking-tcn#4]
Hi,
Thank you for this repo. I have few songs, and I estimated the beats using librosa ( as ground truth) how can I preprocess the data and convert it into a dataset  (X and Y) for training to models?
Cheers,
Suti

**Comment by ben-hayes** [comment]
Hi @SutirthaChakraborty 

You have two options:

1. You can write a custom `torch.utils.data.Dataset` which returns mel spectrograms and a corresponding vector of beat activations (see the Davies & Bock paper for how they represented beats in this vector)
2. (probably easier) You can lay out your data on disk according to the structure of the [ballroom dataset](http://mtg.upf.edu/ismir2004/contest/tempoContest/node5.html) and the accompanying [beat annotations](https://github.com/CPJKU/BallroomAnnotations) and then use the `BallroomDataset` class [provided in this repo](https://github.com/ben-hayes/beat-tracking-tcn/blob/master/beat_tracking_tcn/datasets/ballroom_dataset.py). The beat annotations are just text files with one line per beat, and two space separated values per line: the first is the beat time in seconds and the second is the beat number within the bar. Then you can just use the scripts provided to create spectrograms and train the model.

Hope that helps!

Ben
